### ISSUE TITLE
raft reuse NuRaft?

### ISSUE THREAD

**Issue by billowqiu** [eBay/Gringofts#16]
why the raft module don't use https://github.com/eBay/NuRaft?

**Comment by jackyjia** [comment]
The main reason is we want to master the raft algorithm. And the best way of mastering it is to write the algorithm on our own, put it to test and learn from bugs. In that sense, it's no difference than learning quicksort, which makes you understand quicksort better? Reading the code written by others or writing it your own?

Why we want to understand every single bit of it but use quicksort from a third-party library? Because the in-house system using raft for data replication is quite critical and we cannot tolerate any bug in the implementation or mis-understanding of the algorithm, as they will lead to severe consequences, eBay loses money, seller loses money, firm's reputation got ruined, just name a few.

As to the cost, it turns out that the 2-weeks implementation and test worth the investment. Zero bug since our system goes live. What's more, we can add enhancements, try out different optimizations at our own pace, and provide production support in a timely manner, without relying on anyone else.

They are other reasons, such as readability and understandability (did you read NuRaft's code?), integrate with other layers, support security requirements, etc. But the main reason is we want to master the algorithm to guarantee the quality of our system.
